name: py38_1
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bcrypt=3.2.2
  - black=22.6.0
  - blas=1.0
  - blinker=1.5
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - configparser=5.3.0
  - cryptography=3.4.8
  - databricks-cli=0.17.3
  - entrypoints=0.4
  - fftw=3.3.10
  - gitdb=4.0.9
  - gitpython=3.1.29
  - gunicorn=20.1.0
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - intel-openmp=2021.4.0
  - ld_impl_linux-64
  - libffi=3.3
  - libgfortran-ng
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - mako=1.2.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - oauthlib=3.2.2
  - openssl=1.1.1q
  - pandas=1.4.4
  - paramiko=2.11.0
  - pathspec=0.9.0
  - pip=22.2.2
  - platformdirs=2.5.2
  - prometheus_client=0.15.0
  - prometheus_flask_exporter=0.20.3
  - pycparser=2.21
  - pyjwt=2.6.0
  - pynacl=1.5.0
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.6
  - pywin32-on-windows=0.1.0
  - querystring_parser=1.2.4
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - sqlparse=0.4.3
  - tabulate=0.9.0
  - tk=8.6.12
  - tomli=2.0.1
  - typing_extensions=4.3.0
  - websocket-client=1.4.1
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
  - zlib=1.2.13
  - pip:
    - absl-py==1.0.0
    - aiokafka==0.7.2
    - alembic
    - analytics-python==1.4.0
    - anyio==3.6.2
    - apache-beam==2.42.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asgiref==3.5.2
    - astunparse==1.6.3
    - attrs==20.3.0
    - backoff==1.10.0
    - cachetools==4.2.4
    - click==8.1.3
    - click-params==0.3.0
    - cloudpickle==2.1.0
    - commonmark==0.9.1
    - crcmod==1.7
    - dill==0.3.1.1
    - distro==1.8.0
    - docker==4.4.4
    - docopt==0.6.2
    - ecdsa==0.18.0
    - fastapi==0.75.2
    - fastapi-utils==0.2.1
    - fastavro==1.7.0
    - fasteners==0.18
    - flask==1.1.2
    - flatbuffers==2.0.7
    - gast==0.3.3
    - google-api-core==2.10.2
    - google-api-python-client==1.12.11
    - google-apitools==0.5.32
    - google-auth==2.14.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.4
    - greenlet==2.0.0
    - grpcio==1.44.0
    - h11==0.14.0
    - h5py==2.10.0
    - hdfs==2.7.0
    - httplib2==0.19.1
    - httptools==0.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.2
    - itsdangerous==2.0.1
    - jinja2==2.11.3
    - joblib==1.2.0
    - jsonschema==4.17.0
    - jupyter-server==1.21.0
    - jupyterlab-widgets==1.1.1
    - kafka-python==2.0.2
    - keras==2.8.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==1.1.1
    - ml-metadata==1.8.0
    - ml-pipelines-sdk==1.8.0
    - mlflow
    - mlserver==1.1.0
    - mlserver-mlflow==1.1.0
    - monotonic==1.6
    - nbclassic==0.4.8
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - oauth2client==4.1.3
    - opt-einsum==3.3.0
    - orjson==3.8.1
    - packaging==20.9
    - passlib==1.7.4
    - pexpect==4.8.0
    - pkgutil-resolve-name==1.3.10
    - portpicker==1.5.2
    - proto-plus==1.22.1
    - protobuf==3.19.6
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - py-grpc-prometheus==0.7.0
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.2
    - pydot==1.4.2
    - pymongo==3.13.0
    - pymysql==1.0.2
    - pyparsing==2.4.7
    - pyrsistent==0.19.2
    - python-dotenv==0.21.0
    - python-editor==1.0.4
    - python-jose==3.3.0
    - python-multipart==0.0.5
    - python-terraform==0.10.1
    - pyyaml==5.4.1
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-learn==1.1.1
    - scipy==1.7.1
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - sqlalchemy==1.4.41
    - sqlalchemy2-stubs==0.0.2a29
    - sqlmodel==0.0.8
    - starlette==0.17.1
    - starlette-exporter==0.14.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io==0.24.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==2.1.0
    - terminado==0.17.0
    - testpath==0.6.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - uritemplate==3.0.1
    - urllib3==1.26.12
    - uvicorn==0.17.6
    - uvloop==0.17.0
    - validators==0.18.2
    - watchgod==0.8.2
    - websockets==10.4
    - widgetsnbextension==3.6.1
    - xgboost==1.6.1
    - zenml==0.21.0
    - zstandard==0.19.0
